
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url

speedtestdotnet:

logger:
  default: warning


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml