sensor:
  - platform: google_travel_time
    name: Jonas Distance
    api_key: !secret google_travel_api_key
    scan_interval: 600
    origin: device_tracker.pixel_4_xl
    destination: zone.home
    options:
      mode: driving